# Generated by Django 5.0.1 on 2024-03-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="new",
            field=models.BooleanField(default=True, verbose_name="Nouveau"),
        ),
    ]
