# Generated by Django 5.0.1 on 2024-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="baseline",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dashboard",
            name="category",
            field=models.CharField(
                choices=[
                    ("VUE_ENSEMBLE", "Vue d’ensemble"),
                    ("RECRUTEMENT", "Recrutement"),
                    ("PRESCRIPTEURS", "Prescripteurs"),
                    ("EMPLOYEURS_INCLUSIFS", "Employeurs inclusifs"),
                    ("PUBLICS", "Publics"),
                    (
                        "STATISTIQUES_DES_SERVICES",
                        "Statistiques des services de la Plateforme de l’inclusion",
                    ),
                ],
                default="VUE_ENSEMBLE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dashboard",
            name="metabase_db_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dashboard",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
