# Generated by Django 5.0.1 on 2024-01-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0002_dashboard_baseline_dashboard_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
