# Generated by Django 5.0.6 on 2024-06-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0002_dashboard_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="new",
            field=models.BooleanField(default=False, verbose_name="Nouveau"),
        ),
    ]
