# Generated by Django 5.0.1 on 2024-02-02 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0004_category_dashboard_active_alter_dashboard_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
