# Generated by Django 5.1.7 on 2025-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0005_make_slug_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name="ordre d'affichage"),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="embed_url",
            field=models.URLField(
                blank=True,
                help_text="Si vous souhaitez ajouter une url d'iframe à la place d'un 'Metabase ID', "
                "vous devez de mettre 0 dans le 'Metabase ID' et ajouter une url ci-dessus",
                null=True,
                verbose_name="embed URL",
            ),
        ),
    ]
