# Generated by Django 5.0.1 on 2024-02-02 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0006_category_dashboard_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboards.category",
                verbose_name="Categorie",
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="metabase_db_id",
            field=models.IntegerField(verbose_name="Metabase ID"),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titre"),
        ),
    ]
