# Generated by Django 5.0.1 on 2024-02-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0007_alter_category_title_alter_dashboard_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="tally_id",
            field=models.IntegerField(null=True, verbose_name="Tally Popup ID"),
        ),
    ]
