# Generated by Django 5.0.1 on 2024-02-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0009_alter_dashboard_tally_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="tally_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Tally Popup ID"
            ),
        ),
    ]
