# Generated by Django 5.0.1 on 2024-02-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0010_alter_dashboard_tally_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categorie", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="dashboard",
            options={
                "verbose_name": "Tableau de bord",
                "verbose_name_plural": "Tableaux de bord",
            },
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="baseline",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboards.category",
                verbose_name="Categorie",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Titre"),
        ),
    ]
