# Generated by Django 5.0.1 on 2024-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0011_alter_category_options_alter_dashboard_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dashboard",
            old_name="tally_id",
            new_name="tally_popup_id",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="tally_embed_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Tally Embed ID"
            ),
        ),
    ]
