services:
  postgres:
    container_name: pilotage_django_postgres
    image: postgres:15-alpine
    # Disable some safety switches for a faster postgres: https://www.postgresql.org/docs/current/non-durability.html
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pilotage_django
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5433}:5432"

volumes:
  postgres_data:
