# ruff: noqa: E501

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_survey_conclusion_survey_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esatanswer",
            name="after_reco_situation_list",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_CHANGES", "Maintien sur l’activité professionnelle initiale au sein de l'ESAT"),
                    ("OTHER_ACTIVITY", "Accès à d’autres activités professionnelles au sein de l'ESAT"),
                    ("OTHER_ESAT", "Changement d’ESAT"),
                    (
                        "ESRP",
                        "Accès à une formation via un établissement ou service de réadaptation professionnelle (ESRP)",
                    ),
                    ("TRAINING_COURSE", "Accès à une formation via un organisme de formation"),
                    ("PARTIAL_TIME_WORK", "Accès à un emploi via le temps partagé"),
                    ("LEFT", "Sortie de l'ESAT pour accéder à un emploi en milieu ordinaire ou adapté"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="a l’issue de cette reconnaissance ou validation, quelle a été la suite du parcours des travailleurs et travailleuses concerné(e)s ?",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="budget_commercial",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SURPLUS", "excédentaire"),
                    ("BALANCE", "à l'équilibre"),
                    ("DEFICIT", "déficitaire"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="sur le résultat net de la SEC, étiez-vous",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="budget_commercial_deficit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_100K", "Moins de 100 k€"),
                    ("RANGE_100K_500K", "100 k€ à 500k€"),
                    ("MORE_THAN_500K", "Plus de 500k€"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="de quel montant est-ce déficit ?",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="budget_commercial_excedent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_100K", "Moins de 100 k€"),
                    ("RANGE_100K_500K", "100 k€ à 500k€"),
                    ("MORE_THAN_500K", "Plus de 500k€"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="de quel montant est-cet excédant?",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="budget_social",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SURPLUS", "excédentaire"),
                    ("BALANCE", "à l'équilibre"),
                    ("DEFICIT", "déficitaire"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                help_text="Il s’agit du résultat comptable de l'exercice",
                null=True,
                verbose_name="sur le résultat de clôture de votre Budget de Fonctionnement (Section d'Exploitation du Budget Social), étiez-vous :",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="budget_social_deficit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_100K", "Moins de 100 k€"),
                    ("RANGE_100K_500K", "100 k€ à 500k€"),
                    ("MORE_THAN_500K", "Plus de 500k€"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="de quel montant est-ce déficit ?",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="budget_social_excedent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_THAN_100K", "Moins de 100 k€"),
                    ("RANGE_100K_500K", "100 k€ à 500k€"),
                    ("MORE_THAN_500K", "Plus de 500k€"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="de quel montant est-cet excédant?",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="employee_delegate_formation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRAINING_ORGANIZATION", "par l'intermédiaire d'un organisme de formation"),
                    ("INTERNALLY", "en interne"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="est-ce que le délégué ou la déléguée a bénéficié d'une formation au cours de son mandat pour cette mission :",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="pct_activity_outside",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-20", "De 0% à 20%"),
                    ("21-40", "De 21% à 40%"),
                    ("41-60", "De 41% à 60%"),
                    ("61-80", "De 61% à 80%"),
                    ("81-100", "De 81 à 100%"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="sur l’ensemble de l’activité de l’ESAT, quel est le pourcentage d’activité exercée en dehors de l’établissement ?",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="uaat_inscription",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "Oui"),
                    ("NO", "Non"),
                    ("IN_PROGRESS", "en cours d'inscription"),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="etes-vous inscrit dans la démarche Un Avenir Après le Travail (UAAT) ?",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="year_foresight_in_place",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2026", 2026),
                    ("2025", 2025),
                    ("2024", 2024),
                    ("2023", 2023),
                    ("2022", 2022),
                    ("2021", 2021),
                    ("2020", 2020),
                    ("2019", 2019),
                    ("2018", 2018),
                    ("2017", 2017),
                    ("2016", 2016),
                    ("2015", 2015),
                    ("2014", 2014),
                    ("2013", 2013),
                    ("2012", 2012),
                    ("2011", 2011),
                    ("2010", 2010),
                    ("2009", 2009),
                    ("2008", 2008),
                    ("2007", 2007),
                    ("2006", 2006),
                    ("2005", 2005),
                    ("2004", 2004),
                    ("2003", 2003),
                    ("2002", 2002),
                    ("2001", 2001),
                    ("2000", 2000),
                    ("1999", 1999),
                    ("1998", 1998),
                    ("1997", 1997),
                    ("1996", 1996),
                    ("1995", 1995),
                    ("1994", 1994),
                    ("1993", 1993),
                    ("1992", 1992),
                    ("1991", 1991),
                    ("1990", 1990),
                    ("1989", 1989),
                    ("1988", 1988),
                    ("1987", 1987),
                    ("1986", 1986),
                    ("1985", 1985),
                    ("1984", 1984),
                    ("1983", 1983),
                    ("1982", 1982),
                    ("1981", 1981),
                    ("1980", 1980),
                    ("1979", 1979),
                    ("1978", 1978),
                    ("1977", 1977),
                    ("1976", 1976),
                    ("1975", 1975),
                    ("1974", 1974),
                    ("1973", 1973),
                    ("1972", 1972),
                    ("1971", 1971),
                    ("1970", 1970),
                    ("1969", 1969),
                    ("1968", 1968),
                    ("1967", 1967),
                    ("1966", 1966),
                    ("1965", 1965),
                    ("1964", 1964),
                    ("1963", 1963),
                    ("1962", 1962),
                    ("1961", 1961),
                    ("1960", 1960),
                    ("1959", 1959),
                    ("1958", 1958),
                    ("1957", 1957),
                    ("1956", 1956),
                    ("1955", 1955),
                    ("1954", 1954),
                    ("1953", 1953),
                    ("1952", 1952),
                    ("1951", 1951),
                    ("1950", 1950),
                    ("1949", 1949),
                    ("1948", 1948),
                    ("1947", 1947),
                    ("1946", 1946),
                    ("1945", 1945),
                    ("1944", 1944),
                    ("1943", 1943),
                    ("1942", 1942),
                    ("1941", 1941),
                    ("1940", 1940),
                    ("1939", 1939),
                    ("1938", 1938),
                    ("1937", 1937),
                    ("1936", 1936),
                    ("1935", 1935),
                    ("1934", 1934),
                    ("1933", 1933),
                    ("1932", 1932),
                    ("1931", 1931),
                    ("1930", 1930),
                    ("1929", 1929),
                    ("1928", 1928),
                    ("1927", 1927),
                    ("1926", 1926),
                    ("1925", 1925),
                    ("1924", 1924),
                    ("1923", 1923),
                    ("1922", 1922),
                    ("1921", 1921),
                    ("1920", 1920),
                    ("1919", 1919),
                    ("1918", 1918),
                    ("1917", 1917),
                    ("1916", 1916),
                    ("1915", 1915),
                    ("1914", 1914),
                    ("1913", 1913),
                    ("1912", 1912),
                    ("1911", 1911),
                    ("1910", 1910),
                    ("1909", 1909),
                    ("1908", 1908),
                    ("1907", 1907),
                    ("1906", 1906),
                    ("1905", 1905),
                    ("1904", 1904),
                    ("1903", 1903),
                    ("1902", 1902),
                    ("1901", 1901),
                    ("DO_NOT_KNOW", "Je ne sais pas"),
                ],
                null=True,
                verbose_name="depuis quelle année ce régime de prévoyance est-il mis en œuvre dans l'ESAT ?",
            ),
        ),
        migrations.AlterField(
            model_name="esatanswer",
            name="documents_falclist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("CONTRACT", "Oui : contrat d'accompagnement par le travail"),
                        ("BOOKLET", "Oui : livret d'accueil"),
                        ("REGULATION", "Oui : règlement de fonctionnement"),
                        ("NO", "Non"),
                        ("DO_NOT_KNOW", "Je ne sais pas"),
                    ]
                ),
                blank=True,
                help_text="Le facile à lire et à comprendre (FALC) est une méthode qui a pour but de traduire un langage classique en un langage simplifié.",
                null=True,
                size=None,
                verbose_name="au 31 décembre N-1, les principaux documents destinés aux travailleurs et travailleuses étaient-ils accessibles en FALC ou en communication alternative augmentée ? (contrat d’accompagnement par le travail, livret d’accueil, règlement de fonctionnement, etc.)",
            ),
        ),
    ]
