from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0009_add_and_remove_esat_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="esatanswer",
            old_name="after_reco_situation_list",
            new_name="after_skills_validation",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="annual_ca_dispo",
            new_name="annual_ca_mad",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="cpfreason",
            new_name="cpf_unused_reason",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="mean_employee_age",
            new_name="mean_worker_age",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_conv_exit",
            new_name="nb_conv_exit_agreement",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_esat_conv",
            new_name="nb_esat_agreement",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_acc",
            new_name="nb_worker_acc",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_apprentice",
            new_name="nb_worker_apprentice",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_autodetermination",
            new_name="nb_worker_autodetermination",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_cdd",
            new_name="nb_worker_cdd",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_cdi",
            new_name="nb_worker_cdi",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_code",
            new_name="nb_worker_code",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employeed_cpf_unused",
            new_name="nb_worker_cpf_unused",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_cumul_esat_ea",
            new_name="nb_worker_cumul_esat_ea",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_cumul_esat_ordi",
            new_name="nb_worker_cumul_esat_mot",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_driving_licence",
            new_name="nb_worker_driving_licence",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_duoday",
            new_name="nb_worker_duoday",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_left_esrp",
            new_name="nb_worker_esrp",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_formation_opco",
            new_name="nb_worker_formation_opco",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_ft_job_seekers",
            new_name="nb_worker_ft_job_seekers",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_half_time",
            new_name="nb_worker_half_time",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_interim",
            new_name="nb_worker_interim",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_intern_formation",
            new_name="nb_worker_intern_formation",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_left",
            new_name="nb_worker_left",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_left_asso",
            new_name="nb_worker_left_asso",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_left_ea",
            new_name="nb_worker_left_ea",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_left_private",
            new_name="nb_worker_left_private",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_left_public",
            new_name="nb_worker_left_public",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_dispo_collec",
            new_name="nb_worker_mad_collec",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_dispo_indiv",
            new_name="nb_worker_mad_indiv",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_mispe_mdph",
            new_name="nb_worker_mispe_mdph",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_mispe_rpe",
            new_name="nb_worker_mispe_rpe",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_mobility_inclusion",
            new_name="nb_worker_mobility_inclusion_card",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_new",
            new_name="nb_worker_new",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_pmsmp",
            new_name="nb_worker_pmsmp",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_ordinary_job",
            new_name="nb_worker_previous_mot",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_prof",
            new_name="nb_worker_prof",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_rae",
            new_name="nb_worker_rae_rsfp",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_reinteg",
            new_name="nb_worker_reinteg",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_reinteg_other",
            new_name="nb_worker_reinteg_other",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_service",
            new_name="nb_worker_service",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_temporary",
            new_name="nb_worker_temporary",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_transport",
            new_name="nb_worker_transport",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_rsfp",
            new_name="nb_worker_vae",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_willing_ordinary",
            new_name="nb_worker_willing_mot",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_restau",
            new_name="nb_worker_with_public",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_employee_worked_sunday",
            new_name="nb_worker_worked_sunday",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="pea_convention_signed",
            new_name="pea_agreement_signed",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="retirement_preparation",
            new_name="retirement_preparation_actions",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="nb_uaat_beneficiary",
            new_name="retirement_preparation_nb_workers",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="rpe_convention_signed",
            new_name="rpe_agreement_signed",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="duoday_board",
            new_name="skills_notebook",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="duoday_software_used",
            new_name="skills_notebook_software_used",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="duoday_software_financial_help",
            new_name="software_financial_help",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="duoday_financial_help_type",
            new_name="software_financial_help_type",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="employee_delegate",
            new_name="worker_delegate",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="employee_delegate_formation",
            new_name="worker_delegate_formation",
        ),
        migrations.RenameField(
            model_name="esatanswer",
            old_name="employee_delegate_hours_credit",
            new_name="worker_delegate_hours_credit",
        ),
    ]
