# Generated by Django 5.1.13 on 2026-01-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0013_new_feedbacks"),
    ]

    operations = [
        migrations.AddField(
            model_name="esatanswer",
            name="step_feedback",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
