# Generated by Django 5.0.1 on 2024-02-23 09:48
from django.db import migrations


def create_groups(apps, schema_migration):

    UserGroup = apps.get_model("users", "UserGroup")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    add_category = Permission.objects.get(codename="add_category")
    change_category = Permission.objects.get(codename="change_category")
    delete_category = Permission.objects.get(codename="delete_category")
    view_category = Permission.objects.get(codename="view_category")

    editors_permissions = [
        add_category,
        change_category,
        delete_category,
        view_category,
    ]

    editors = Group(name="editors")
    editors.save()
    editors.permissions.set(editors_permissions)

    subscribers = Group(name="subscribers")
    subscribers.save()
    subscribers.permissions.add(view_category)

    for user in UserGroup.objects.all():
        if user.role == "EDITOR":
            editors.user_set.add(user)
        if user.role == "SUBSCRIBER":
            subscribers.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [("dashboards", "0001_initial")]

    operations = [migrations.RunPython(create_groups)]
